### ISSUE TITLE
Backup of past flag state

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-flags-api#31]
As far as I can see if we accidentally/maliciously deleted all/many/some flags there is no historical backup, and therefore no quick way to undo (not even manually by re-entering flags as there's no way to discover which flags have been removed). Can we protect ourselves against this?

@matthew-andrews

**Comment by matthew-andrews** [comment]
There is a backup of sorts…… AWS S3 keeps all the historical versions.
Suggest any restore solution is based off of this.
